version: '3.3'

services:

   postgres:
   
      image: postgres:14-alpine
      
      container_name: postgres

      restart: always

      ports:
         - 44:5432
         
      volumes:
         - ./postgresdata:/var/lib/postgresql/data
         
      env_file:
         - .env.postgres
   
   dbmaker:
   
      image: ivanduque0/dbmakermanagerbot:ArmV6l
      
      volumes:
         - ./dbmaker:/app
         
      command: python3 codigo.py
         
      env_file: .env.manager
   
      depends_on:
         - postgres

   dbmanagerall:
   
      image: ivanduque0/dbmakermanagerbot:ArmV6l
      # image: ivanduque0/dbmakerman:agerV0.3

      container_name: dbmanagerall
      
      restart: always
      
      command: python3 codigo.py
      
      volumes:
         - ./dbmanagerall:/app
         
      env_file:
         - .env.manager
      
      depends_on:
         - postgres

   dispositivos:
   
      image: ivanduque0/dbmakermanagerbot:ArmV6l

      container_name: dispositivos
      
      restart: always
      
      command: python3 codigo.py
      
      volumes:
         - ./dispositivosweb:/app

      env_file:
         - .env.manager
      
      depends_on:
         - postgres

   # telegrambot:
   
   #    image: ivanduque0/dbmakermanagerbot:ArmV6l

   #    container_name: telegrambot
      
   #    restart: always
      
   #    command: python3 codigo.py
      
   #    volumes:
   #       - ./botelegram:/app

   #    env_file:
   #       - .env.manager
      
   #    depends_on:
   #       - postgres

   wifilocal:
   
      image: ivanduque0/dbmakermanagerbot:ArmV6l

      container_name: wifilocal
      
      restart: always
      
      command: python3 codigo.py
      
      volumes:
         - ./servidorlocalwifi:/app

      ports:
         - 43157:43157

      env_file:
         - .env.manager
      
      depends_on:
         - postgres

   aperturas:
   
      image: ivanduque0/dbmakermanagerbot:ArmV6l

      container_name: aperturas
      
      restart: always
      
      command: python3 codigo.py
      
      volumes:
         - ./aperturas:/app

      env_file:
         - .env.manager
      
      depends_on:
         - postgres

   ping:
   
      image: ivanduque0/dbmakermanagerbot:ArmV6l

      container_name: ping
      
      restart: always
      
      command: python3 codigo.py
      
      volumes:
         - ./pingdispositivos:/app

      env_file:
         - .env.manager
      
      depends_on:
         - postgres

         
   # dbmanagerusuarios:
   
   #    image: ivanduque0/dbmakermanagerbot:ArmV6l
      
   #    restart: always
      
   #    command: python3 codigo.py
      
   #    volumes:
   #       - ./dbmanagerusuarios:/app
         
   #    env_file:
   #       - .env.manager
      
   #    depends_on:
   #       - postgres
         
   # dbmanagerhorarios:
   
   #    image: ivanduque0/dbmakermanagerbot:ArmV6l
      
   #    restart: always
      
   #    command: python3 codigo.py
      
   #    volumes:
   #       - ./dbmanagerhorarios:/app
         
   #    env_file:
   #       - .env.manager
      
   #    depends_on:
   #       - postgres
         
   # dbmanagerinteracciones:
   
   #    image: ivanduque0/dbmakermanagerbot:ArmV6l
      
   #    restart: always
      
   #    command: python3 codigo.py
      
   #    volumes:
   #       - ./dbmanagerinteracciones:/app

   #    env_file:
   #       - .env.manager
      
   #    depends_on:
   #       - postgres

   # dbmanagerid:
   
   #    image: ivanduque0/dbmakermanagerbot:ArmV6l
      
   #    restart: always
      
   #    command: python3 codigo.py
      
   #    volumes:
   #       - ./dbmanagertelegramid:/app

   #    env_file:
   #       - .env.manager
      
   #    depends_on:
   #       - postgres
         